name: posyandu
description: Aplikasi Pemantauan Kesehatan Ibu dan Anak.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  image: ^4.1.3

# Flutter app launcher icon configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "assets/logo.jpg"
  adaptive_icon_foreground_scale_factor: 0.65 # Scale down the foreground image
  image_size: 256 # Set smaller base image size
  # You can also add the following settings:
  # android_adaptive_icon_padding: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo.jpg
    
